#!/bin/bash

# Bash script to test question 1 of homework 1
# Usage :- chmod +x q1test.sh
#          ./q1test.sh


#-------------------------------------------------------------------
# TEST CASE# 1 : To test whether the output generated by the program 
#                is correct or not. 
#-------------------------------------------------------------------
echo "Test 1: Running the program to diff actual vs expected output...."
./homework q1 > actual_result.out
diff -u --label='your output' --label='expected output' actual_result.out - <<EOF || { echo TEST q1.1 FAILED; exit; }
Hello world
EOF

#-------------------------------------------------------------------
# TEST CASE# 2 : Running Valgrind to check for memory leaks in the  
#                program. 
#-------------------------------------------------------------------
echo "Test 2: Running valgring to test for memory errors....." 
valgrind ./homework q1 >& actual_result.out
if grep -v "ERROR SUMMARY: 0 errors from 0 contexts" actual_result.out ; then
    echo "Valgrind run successfull. No Memory Leaks"
    echo "SUCCESS ====> TEST q1.2 passed"
else
    echo "Valgrind gave errors..... Need to resolve."
fi
