#!/bin/bash

# Bash script to test question 3 of homework 1
# Usage :- chmod +x q2test.sh
#          ./q2test.sh

#-------------------------------------------------------------------
# TEST CASE# 1 : To check that basic execution works i.e. command 
#                does not fail. 
#-------------------------------------------------------------------
echo "Test 1: Test for basic execution of the program"
./homework q3 > actual_result.out || { echo TEST q3.1 FAILED; exit; }
if [ "$?" = "0" ] ; then
    echo "Run successfull"
    echo "SUCCESS ====> TEST q3.1 passed"
else
    echo "Basic execution failed!!!!"
fi
#-------------------------------------------------------------------
# TEST CASE# 2 : To test whether the output generated by the program
#                is correct and in order. 
#-------------------------------------------------------------------
echo "Test 2: Test for correctness of the output of the program"
./homework q3 > actual_result.out
diff -u --label='your output' --label='expected output' actual_result.out - <<EOF || { echo TEST q3.2 FAILED; exit; }
program 1
program 2
program 1
program 2
program 1
program 2
program 1
program 2
EOF
